@startuml
!theme vibrant
repeat :**GUI**\n Criação do modelo via interface;

:**Simulção**
Simulação //on-site//;

repeat while (O usuário está contente com o modelo?) is (    não)
-> sim;

:**Exportação**
Simulação //off-site//;
@enduml