@startuml plot

struct PlotInfo {
    + title: String
    + xlabel: String
    + ylabel: String
    + data: CSVData
}

struct PlotLayout {
    + rows: u32
    + cols: u32
    + number_of_tabs: u32
    + active_tabs: Vec<u32>
}

struct CSVData {
    + labels: Vec<String>
    + lines: Vec<Vec<f64>>
    + time: Vec<f64>
}

PlotInfo "1" *-- "1" CSVData

@enduml