name: Compile LaTeX PDF and PlantUML diagrams

on:
  push:
    paths:
      - '**.tex'
      - 'imgs/**'
      - '.github/**/*.yml'
      - 'diagrams/img/**'
      - '**.puml'

jobs:
  latexbuild:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            diagrams_src:
              - 'diagrams/src/**'
      
      - name: Compile Diagrams
        if: steps.changes.outputs.diagrams_src == 'true'
        shell: bash
        run: |
          docker run \
            -v ./diagrams/src:/src \
            -v ./diagrams/img:/img \
            ghcr.io/plantuml/plantuml /src -o /img

      - name: Build PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ufsj-abntex2.tex

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update PDF
          branch: ${{ github.ref_name }}
          commit_user_name: actions-user
          commit_user_email: actions@github.com
          commit_author: actions-user <actions@github.com>
          file_pattern: 'ufsj-abntex2.pdf diagrams/img/**'
